### ISSUE TITLE
Importmaps update delay

### ISSUE THREAD

**Issue by mhenrixon** [hopsoft/turbo_boost-commands#103]
I am not experienced enough in JavaScript and importmaps to understand why the version on ga.jspm.io is lagging.  

I must wait a week or so for every release before updating. It isn't a big deal, but I figured I'll let you know if it is something you can address on your side @hopsoft!

Thanks for the fantastic tool!

https://ga.jspm.io/npm:@turbo-boost/commands@0.0.14/app/assets/builds/@turbo-boost/commands.js tells me it isn’t there but according to `bin/importmap outdated` it should be there!

![CleanShot 2023-09-07 at 11 11 57@2x](https://github.com/hopsoft/turbo_boost-commands/assets/106795/9e50b6a1-d4b8-419f-997c-f2afac8c0e2d)

**Comment by hopsoft** [comment]
This is interesting. No idea why it would take so long. Will need to investigate.

**Comment by hopsoft** [comment]
This should be resolved with the addition of VERSION to the JavaScript build.
