### ISSUE TITLE
Using turbo boost elements with cancancan  

### ISSUE THREAD

**Issue by mhenrixon** [hopsoft/turbo_boost-commands#110]
I am trying to build a minimal CMS. For reasons you know about, I decided to give turbo_boost a try. First, to show how I want it to work, I recorded a little video without the `can?` check. 

![CleanShot 2023-10-20 at 12 57 20](https://github.com/hopsoft/turbo_boost-commands/assets/106795/a6794ed9-43c9-424a-b30d-b8c8524b7252)

Now, if I add cancancan and a `can?` check, I can only click once. Anything within that `can?` check is rendered only on page load, not on clicking the command buttons.

```erb
<%= tag.div id: dom_id(article) do %>
  <% settings_tag = dom_id(article, :settings) %>
  <% edit_body_tag = dom_id(article, :edit_body) %>

  <% if can?(:edit, article) %>
    <div class="article-commands flex space-x-4 align-right">
      <%= toggle_trigger_tag renders: current_partial_path,
                             morphs: dom_id(article),
                             controls: settings_tag,
                             locals: { article: article },
                             assigns: { article: article } do %>

        <% if toggle_target_collapsed? settings_tag %>
          <%= link_to request.path, id: "edit-settings-cmd" do %>
            <%= heroicon "cog", variant: :outline, class: "h-6 w-auto" %>
          <% end %>
        <% else %>
          <%= link_to request.path, id: "show-article-cmd" do %>
            <%= heroicon "x-mark", variant: :outline, class: "h-6 w-auto" %>
          <% end %>
        <% end %>
      <% end %>

      <%= toggle_trigger_tag renders: current_partial_path,
                             morphs: dom_id(article),
                             controls: edit_body_tag,
                             locals: { article: article },
                             assigns: { article: article } do %>

        <% if toggle_target_collapsed? edit_body_tag %>
          <%= link_to request.path, id: "edit-body-cmd" do %>
            <%= heroicon "pencil-square", variant: :outline, class: "h-6 w-auto" %>
          <% end %>
        <% else %>
          <%= link_to request.path, id: "show-article2-cmd" do %>
            <%= heroicon "x-mark", variant: :outline, class: "h-6 w-auto" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>
```

Something like https://github.com/hotwired/turbo-rails/issues/243, perhaps?

PS. I opened the issue on turbo_boost-commands instead of turbo_boost-elements because it doesn't have much to do with elements, as it is the command that executes that is missing a current user, current ability, or some such. 

If that is a wrong assumption, let me know, and I will close and open an issue on elements instead.

Now that I feel lighter, I will debug this issue myself. Wish me luck 🍀

**Comment by mhenrixon** [comment]
@hopsoft I'm having a hard time figuring this out. What I can tell is that whatever I do to set my `Current.user` etc, is not being run so I am guessing turbo_boost is hijacking the request completely.

**Comment by julianrubisch** [comment]
hmm the first question would be if you see anything in the JS console going wrong. then, commands will fail loudly if anything goes wrong on the server side, so... this might not be the case

looking at the elements' command it does use `prevent_controller_action`, so you might be correct in that there could be some `Current` setup missing: https://github.com/hopsoft/turbo_boost-elements/blob/main/app/commands/turbo_boost/elements/toggle_command.rb#L4

other than that I fear I only have the canonical answer of "please provide us an MVCE" 🤷‍♂️

**Comment by mhenrixon** [comment]
> looking at the elements' command it does use `prevent_controller_action`, so you might be correct in that there could be some `Current` setup missing: https://github.com/hopsoft/turbo_boost-elements/blob/main/app/commands/turbo_boost/elements/toggle_command.rb#L4

This seems to be exactly the problem. Any chance to run some before_command hook or otherwise set up the necessary current attributes? I'd also greatly appreciate any alternative suggestions. 

It seems like a perfectly valid use case to me so curious how to continue.

**Comment by julianrubisch** [comment]
@hopsoft you must've come across this?

Typically this is set in application_command but with element I suppose we'd have to supply a config option?

**Comment by hopsoft** [comment]
Commands run as a before action, but they are prepended and execute before other before actions. This means you'll need to ensure that you perform any setup that the command may need like `current_user`. You can do this for all commands in your ApplicationCommand.

Here's an example of how to do this. https://github.com/hopsoft/turbo_boost-commands/blob/eb2f5cd4a533ec3fbab38d6aed1e16804f77a474/test/dummy/app/controllers/application_controller.rb

**Comment by mhenrixon** [comment]
> Commands run as a before action, but the command before action is [effectively prepended](https://github.com/hopsoft/turbo_boost-commands/blob/eb2f5cd4a533ec3fbab38d6aed1e16804f77a474/lib/turbo_boost/commands/engine.rb#L33) and executes before other before actions. This means you'll need to ensure that you perform any setup that the command may need like `current_user` or `Current.user`. You can do this for all commands in your ApplicationCommand.
> 
> Here's an example of how to do this. https://github.com/hopsoft/turbo_boost-commands/blob/eb2f5cd4a533ec3fbab38d6aed1e16804f77a474/test/dummy/app/controllers/application_controller.rb

That works like a charm; just some documentation missing!

**Comment by hopsoft** [comment]
Yeah. I definitely need to carve out some time to improve the docs and demos.

**Comment by hopsoft** [comment]
Closing in lieu of #112
