### ISSUE TITLE
Cannot Access `Current` Helpers with `prevent_controller_action` in `TurboBoost::Commands::Command`

### ISSUE THREAD

**Issue by ivorpad** [hopsoft/turbo_boost-commands#111]
#### Description:
When using the `TurboBoost::Commands::Command` class in conjunction with the `prevent_controller_action` method, I've found that it's impossible to access the `Current` module. This is causing issues, especially when trying to fetch context-based data.

#### Steps to reproduce:
1. Create a`Command < TurboBoost::Commands::Command` class and use the `prevent_controller_action` method inside it.
2. Attempt to access any `Current` helper or another Rails helper method.
3. Observe the inability to access or call these methods.

#### Expected Behavior:
I expected to be able to access the `Current` helpers inside the `TurboBoost::Commands::Command` class, even when the `prevent_controller_action` method is used.

#### Actual Behavior:
The `Current` module are inaccessible, which has caused data flow issues in our application.

#### Potential Solutions or Workarounds:
Currently, I'm passing necessary data from the client to the server via `data-` attributes. While this works, it would be more streamlined if the `Current` context and other helpers were accessible directly. Moreover, passing sensitive data like the current user or account through `data-` attributes poses a risk, as they can be tampered with on the client side.

**Comment by hopsoft** [comment]
Does attempting to access `Current` raise an error or are the values missing? If the values are missing, then see this answer for a solution/work-around. https://github.com/hopsoft/turbo_boost-commands/issues/110#issuecomment-1822223282

**Comment by hopsoft** [comment]
Closing in lieu of #112
