### ISSUE TITLE
Using reflex produces error with validatng server token

### ISSUE THREAD

**Issue by acetinick** [hopsoft/turbo_boost-commands#36]
![image](https://user-images.githubusercontent.com/571649/201486304-d7153a49-88ff-428f-b2da-3a44b1e1217c.png)

**Comment by hopsoft** [comment]
What version of the lib are you using? Also, do you have TurboReady installed and configured?

**Comment by hopsoft** [comment]
Be sure to include the TurboReflex meta tag in your layouts. https://github.com/hopsoft/turbo_reflex/blob/main/test/dummy/app/views/layouts/application.html.erb#L8 

I'll be sure to update the Reflex Behavior docs with this step. Let me know if that resolves things for you.

**Comment by hopsoft** [comment]
It appears that there may be a bug with the [frame driver](https://github.com/hopsoft/turbo_reflex/blob/main/app/javascript/drivers/frame.js) that doesn't apply the TurboStream which is used to update the token. It's possible to [opt-out of token validation](https://github.com/hopsoft/turbo_reflex/blob/main/test/dummy/config/initializers/turbo_reflex.rb#L24) which is currently the best workaround.

**Comment by bricolage** [comment]
@hopsoft I'm getting this too, running on 0.0.3 and turbo-rails 1.3.2. 

First of all amazing set of new tools, thank you. Second, I am happy to opt-out of token validation, but any sense of how this might get addressed, or is there anything that might be helpful to resolve it?

**Comment by hopsoft** [comment]
Yes. We have an idea to move token updates etc... outside the purview of Turbo Streams and handle it differently. I'll update the ticket with details once I put focus back onto this.

**Comment by hopsoft** [comment]
We should move the token to a cookie to avoid race conditions triggered by issuing commands in quick succession. Note that we'll continue to use the meta element to hold ephemeral state etc.

**Comment by hopsoft** [comment]
Note that the next release defaults token validation as `false`

```ruby
config.turbo_boost_commands[:validate_client_token] = false
```

I'll revisit this and work the kinks out in a subsequent release.
