### ISSUE TITLE
handle_command_event has an incorrect message signature

### ISSUE THREAD

**Issue by pdenya** [hopsoft/turbo_boost-commands#86]
# Steps to duplicate

introduce a rendering error to any partial rendered from a command.

# Expected

Receive error message from partial

# Actual

Receive this error message instead

```
Error in AnnotationsUpdateSidebar#perform! #<ArgumentError: wrong number of arguments (given 2, expected 1)> ["/Users/pdenya/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/turbo_boost-commands-0.0.11/lib/turbo_boost/commands/runner.rb:174:in `handle_command_event'", "/Users/pdenya/.rbenv/versions/3.1.3/lib/ruby/3.1.0/observer.rb:222:in `block in notify_observers'", "/Users/pdenya/.rbenv/versions/3.1.3/lib/ruby/3.1.0/observer.rb:221:in `each'", "/Users/pdenya/.rbenv/versions/3.1.3/lib/ruby/3.1.0/observer.rb:221:in `notify_observers'"]
```

# Cause

runner.rb#174 is either getting called incorrectly or has an incorrect message signature

```ruby 
def handle_command_event(event, error: nil)
```

Something like this bypasses the error but still doesn't seem to be entirely correct so I didn't submit a PR.

```ruby 
def handle_command_event(event, error = nil)
```

*Edit:* On second look, pretty sure the solution is:

```ruby 
def handle_command_event(event, options = {})
  error = options[:error]
```

# ENV
ruby 3.1.3
turbo boost command 0.0.11

# Temp solution

For anyone else running into this, you can modify `runner.rb` which you'll have the location of from your error message as a temp fix. Change `handle_command_event` to the following:

```ruby
  def handle_command_event(event, options = {})
    error = options[:error]
    # print the actual error, this doesn't seem to happen automatically
    Rails.logger.error error.message if error
    Rails.logger.error error.backtrace.join("\n") if error
    case event
    when :aborted
      prevent_controller_action error: error
      append_streams_to_response_body
    when :errored then prevent_controller_action(error: error)
    when :performed then prevent_controller_action if should_prevent_controller_action?
    end
  end
```

**Comment by bricolage** [comment]
+1 I'm running into this too, it swallows any view errors

**Comment by bricolage** [comment]
@hopsoft hey Nate, any comments? I can submit a PR. Also any comments on the future of turbo-boost?

**Comment by hopsoft** [comment]
Thank you for the report. Will try to improve error handling here before cutting the next release... which should be soon. 🤞🏻
